services:
  engine:
    build: engine/
    image: chorus-engine:latest

  server:
    build: server/
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/chorus
      - SECRET_KEY=your_secret_key
    depends_on:
      db:
        condition: service_healthy
        restart: true
      engine:
        condition: service_started
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chorus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
