"""anonymous users

Revision ID: 079d5bd30d3b
Revises: 75cdc2b46274
Create Date: 2025-12-11 23:18:19.714723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079d5bd30d3b'
down_revision: Union[str, None] = '75cdc2b46274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('is_anonymous', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'is_anonymous')
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
