"""conversation customization fields

Revision ID: 1e8fa719ca11
Revises: 079d5bd30d3b
Create Date: 2026-01-05 22:48:09.901527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8fa719ca11'
down_revision: Union[str, None] = '079d5bd30d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('theme_color', sa.String(length=7), nullable=True))
    op.add_column('conversations', sa.Column('header_name', sa.String(length=200), nullable=True))
    op.add_column('conversations', sa.Column('knowledge_base_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'knowledge_base_content')
    op.drop_column('conversations', 'header_name')
    op.drop_column('conversations', 'theme_color')
    # ### end Alembic commands ###
