"""approved field in comments

Revision ID: 4421815d5b1c
Revises: df39cbdabaff
Create Date: 2025-03-11 19:25:03.242495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4421815d5b1c'
down_revision: Union[str, None] = 'df39cbdabaff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'approved')
    # ### end Alembic commands ###
