"""Conversation display unmoderated option

Revision ID: 5a6e967ea8c4
Revises: 4421815d5b1c
Create Date: 2025-04-07 22:42:46.654281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a6e967ea8c4"
down_revision: Union[str, None] = "4421815d5b1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("comments", "approved", existing_type=sa.BOOLEAN(), nullable=True)
    op.add_column(
        "conversations",
        sa.Column(
            "display_unmoderated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("conversations", "display_unmoderated", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "display_unmoderated")
    op.alter_column("comments", "approved", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
