"""add creation and update dates

Revision ID: 717a1dc80930
Revises: 5a6e967ea8c4
Create Date: 2025-06-24 19:16:52.751898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717a1dc80930'
down_revision: Union[str, None] = '5a6e967ea8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('conversations', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('conversations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_cluster', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_pca', sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('votes', sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'date_created')
    op.drop_column('user_pca', 'date_updated')
    op.drop_column('user_cluster', 'date_updated')
    op.drop_column('conversations', 'is_active')
    op.drop_column('conversations', 'date_created')
    op.drop_column('comments', 'date_created')
    # ### end Alembic commands ###
