"""unique friendly links

Revision ID: 73905afe8fee
Revises: cd77391f08b9
Create Date: 2025-07-12 16:44:40.426590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73905afe8fee'
down_revision: Union[str, None] = 'cd77391f08b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conversations', ['user_friendly_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='unique')
    # ### end Alembic commands ###
