"""allow commenting and voting booleans

Revision ID: 75cdc2b46274
Revises: 73905afe8fee
Create Date: 2025-12-08 18:37:01.961753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cdc2b46274'
down_revision: Union[str, None] = '73905afe8fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('allow_comments', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('conversations', sa.Column('allow_votes', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'allow_votes')
    op.drop_column('conversations', 'allow_comments')
    # ### end Alembic commands ###
