"""user friendly links for conversations

Revision ID: cd77391f08b9
Revises: 717a1dc80930
Create Date: 2025-07-12 16:38:02.900208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd77391f08b9'
down_revision: Union[str, None] = '717a1dc80930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_friendly_link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'user_friendly_link')
    # ### end Alembic commands ###
