name: Build and Publish to GitHub Pages

on:
  push:
    branches:
      - "storybook*"
      - "ma*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - run: npm ci
        working-directory: docs

      - run: npm run build
        working-directory: docs

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: false
          install_command: cd client && npm ci
          build_command: cd client && npm run build-storybook -- --output-dir ../docs/build/storybook
          path: docs/build